"use strict";

require("core-js/modules/es6.object.define-property");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPLOAD_FILES_PROGRESS = exports.UPLOAD_FILES_FAILED = exports.UPLOAD_FILES_SUCCESS = exports.UPLOAD_FILES_START = void 0;
var UPLOAD_FILES_START = 'UPLOAD_FILES_START';
exports.UPLOAD_FILES_START = UPLOAD_FILES_START;
var UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
exports.UPLOAD_FILES_SUCCESS = UPLOAD_FILES_SUCCESS;
var UPLOAD_FILES_FAILED = 'UPLOAD_FILES_FAILED';
exports.UPLOAD_FILES_FAILED = UPLOAD_FILES_FAILED;
var UPLOAD_FILES_PROGRESS = 'UPLOAD_FILES_PROGRESS';
exports.UPLOAD_FILES_PROGRESS = UPLOAD_FILES_PROGRESS;