export const UPLOAD_FILES_START = 'UPLOAD_FILES_START';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAILED = 'UPLOAD_FILES_FAILED';
export const UPLOAD_FILES_PROGRESS = 'UPLOAD_FILES_PROGRESS';
